/**
 * System facility-code generation.
 *
 * Codes are ALWAYS generated by the system, never chosen by users — this
 * prevents duplicates, impersonation, and confusing codes. Format is
 * PREFIX-#### (e.g. GREEN-4821): the strongest word from the facility name,
 * a dash, and a random 4-digit number. Uniqueness is verified against the set
 * of codes already taken.
 */

// Generic words that don't identify a facility — skipped when picking a prefix.
const STOPWORDS = new Set([
  "THE", "OF", "AND", "A", "AN", "AT", "FOR",
  "CARE", "CENTER", "CENTRE", "RECOVERY", "REHAB", "REHABILITATION",
  "HEALTH", "HEALTHCARE", "MEDICAL", "NURSING", "HOME", "HOMES",
  "FACILITY", "CLINIC", "HOSPITAL", "SKILLED", "LIVING", "ASSISTED",
  "SENIOR", "SENIORS", "GROUP", "COMMUNITY", "SERVICES", "INC", "LLC",
]);

/** Pick the strongest identifiable word from a facility name → uppercase prefix. */
export function prefixFromName(name: string): string {
  const words = (name || "")
    .toUpperCase()
    .replace(/[^A-Z0-9\s]/g, " ")
    .split(/\s+/)
    .map((w) => w.replace(/[^A-Z]/g, "")) // letters only for the prefix
    .filter((w) => w.length >= 2);

  if (words.length === 0) return "REHUB";

  // First non-stopword wins; fall back to the longest word, then the first.
  const significant =
    words.find((w) => !STOPWORDS.has(w)) ??
    words.slice().sort((a, b) => b.length - a.length)[0] ??
    words[0];

  return significant.slice(0, 8);
}

function randomSuffix(): string {
  return String(Math.floor(1000 + Math.random() * 9000)); // 1000–9999
}

/**
 * Generate a unique facility code from a name.
 * @param name        Facility name (e.g. "Green Valley Recovery").
 * @param takenCodes  Codes already in use (compared dash/case-insensitively).
 */
export function generateFacilityCode(name: string, takenCodes: string[] = []): string {
  const prefix = prefixFromName(name);
  const squash = (c: string) => c.toUpperCase().replace(/[^A-Z0-9]/g, "");
  const taken = new Set(takenCodes.map(squash));

  for (let attempt = 0; attempt < 50; attempt++) {
    const code = `${prefix}-${randomSuffix()}`;
    if (!taken.has(squash(code))) return code;
  }
  // Extremely unlikely fallback: widen the numeric space.
  return `${prefix}-${Date.now().toString().slice(-5)}`;
}
